---
title: "Weekly Assignment 4"
author: "John Dreyfous"
date: "1/31/2023"
output: html_document
---

#### Question 1: Simulate a brand new data frame (the type of data is up to you) and conduct a statistical analysis in R using 2 variables. Create a basic ggplot that goes with the analysis.

This work below is a made up data set of the relationship between Tadpole Body length and days spent in water. 

```{r}
### LOAD LIBRARIES
library(tidyverse)
library(ggthemes)

```
```{r}
########## SIMULATE NEW DATE FRAME##########3
Time_Water <- rnorm(n=50, mean=100, sd=25)
  Body_Length <- rnorm(n=50, mean=10, sd=2)
  dataFrame <- data.frame(Time_Water, Body_Length, stringsAsFactors = F)
df<-dataFrame[order(dataFrame$Body_Length, dataFrame$Time_Water),]
df
```

```{r}
##### STATISTICAL ANALYSES #####
lmModel<- lm(Body_Length~Time_Water, data=df)
summary(lmModel)
summary(lmModel)$"r.squared"
```
```{r}
##### GGPLOT ###
 frogPlot <- ggplot(data=df, aes(x=Time_Water, y=Body_Length))+
      geom_point(size=2.5, color="darkolivegreen")+
      stat_smooth(method=lm, se=0.99)
  frogPlot+ xlab("Time in Water (days)")+
  ylab("Tadpole Body Length (cm)")
```

